# Generated by Django 2.2.3 on 2019-07-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('duration', models.DurationField()),
                ('genre', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
